// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"neurokin/views/layouts"
	"neurokin/views/shared"
)

func Login() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"w-full flex flex-col items-center justify-center pt-[100px] sm:w-[80%] container max-w-[1600px] sm:justfify-between sm:flex-row\"><div class=\"flex flex-col bg-green-500 p-[1.5px] sm:p-[5px] rounded-[10px] sm:rounded-[16px] w-[90%] sm:w-[40%]\"><div class=\"bg-green-500 flex gap-x-[4px] sm:gap-x-[6px] p-[6px] sm:p-2.5 rounded-t-[10px] sm:rounded-t-[16px]\"><div class=\"bg-white rounded-full w-[9px] h-[9px] sm:w-[12px] sm:h-[12px]\"></div><div class=\"bg-white rounded-full w-[9px] h-[9px] sm:w-[12px] sm:h-[12px]\"></div><div class=\"bg-white rounded-full w-[9px] h-[9px] sm:w-[12px] sm:h-[12px]\"></div></div><div class=\"bg-white rounded-b-[10px] sm:rounded-b-[16px] p-6 \"><h1 class=\"text-4xl mb-4 sm:mb-12\">Welcome back!</h1><form action=\"/login\" method=\"post\" class=\"flex flex-col items-center w-full\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = shared.Input("email", "email", "Email", "true").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"h-6 w-full\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = shared.Input("password", "password", "Password", "true").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"h-3 w-full\"></div><a href=\"/forgot-password\" class=\"text-black opacity-50 underline w-full\">Forgot password?</a> <button type=\"submit\" class=\"w-full sm:w-1/2 bg-pink-500 hover:bg-pink-700 transition-all text-white font-bold py-2 px-4 rounded-[8px] mt-8 focus:outline-none focus:shadow-outline\">Login</button><p class=\"text-center mt-4 mb-4 opacity-50\">Or, for passwordless login</p><button class=\"w-full sm:w-1/2 transition-all hover:scale-105   text-black py-2 px-4 border-black border-solid border rounded-[8px] focus:outline-none focus:shadow-outline\">Sign in with Google</button></form></div></div><div class=\"flex flex-col items-center\"><image src=\"/public/images/girl-yellow.png\" class=\"hidden md:block w-[400px] mt-8\"></image><div class=\"flex flex-col bg-green-500 p-[1.5px] sm:p-[5px] rounded-[10px] sm:rounded-[16px] min-w-0 w-[90%] sm:w-auto sm:min-w-[650px] mt-[14px]\"><div class=\"bg-green-500 flex gap-x-[4px] sm:gap-x-[6px] p-[6px] sm:p-2.5 rounded-t-[10px] sm:rounded-t-[16px]\"><div class=\"bg-white rounded-full w-[9px] h-[9px] sm:w-[12px] sm:h-[12px]\"></div><div class=\"bg-white rounded-full w-[9px] h-[9px] sm:w-[12px] sm:h-[12px]\"></div><div class=\"bg-white rounded-full w-[9px] h-[9px] sm:w-[12px] sm:h-[12px]\"></div></div><div class=\"bg-white rounded-b-[10px] sm:rounded-b-[16px] p-6 \"><div class=\"w-full bg-pink-500 hover:bg-pink-700 transition-all text-white font-bold py-2 px-4 rounded-[8px] focus:outline-none focus:shadow-outline flex items-center justify-center\"><a href=\"/signup\">Switch to Sign up</a></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
