// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"neurokin/views/layouts"
	"neurokin/views/shared"
)

func Signup() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"min-h-full lg:flex-1 lg:flex lg:items-center lg:justify-center\"><div class=\"container w-full flex flex-col lg:flex-row items-center justify-center py-10 px-2 lg:p-0 lg:gap-x-20 mx-auto\"><div class=\"flex flex-col bg-green-500 p-[1.5px] lg:p-[5px] rounded-[10px] lg:rounded-[16px] w-full lg:w-[40%]\"><div class=\"bg-green-500 flex gap-x-[4px] lg:gap-x-[6px] p-[6px] lg:p-2.5 rounded-t-[10px] lg:rounded-t-[16px]\"><div class=\"bg-white rounded-full w-[9px] h-[9px] lg:w-[12px] lg:h-[12px]\"></div><div class=\"bg-white rounded-full w-[9px] h-[9px] lg:w-[12px] lg:h-[12px]\"></div><div class=\"bg-white rounded-full w-[9px] h-[9px] lg:w-[12px] lg:h-[12px]\"></div></div><div class=\"bg-white rounded-b-[10px] lg:rounded-b-[16px] p-6 \"><h1 class=\"text-4xl mb-4 lg:mb-12\">Let's get started.</h1><form id=\"signup-form\" hx-post=\"/signup\" enctype=\"multipart/form-data\" hx-target=\"#error-message\" hx-swap=\"innerHTML\" hx-on class=\"flex flex-col items-center w-full\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = shared.Input("email", "email", "Email", "true").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"h-6 w-full\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = shared.Input("password", "password", "Password", "true").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"h-6 w-full\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = shared.Input("conf-password", "password", "Re-enter your password", "true").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"h-3 w-full\"></div><div id=\"error-message\" class=\"font-bold text-red-500 text-center\"></div><div class=\"h-3 w-full\"></div><button type=\"submit\" class=\"w-full lg:w-1/2 bg-pink-700 hover:bg-pink-500 transition-all text-white font-bold py-2 px-4 rounded-[8px] focus:outline-none focus:shadow-outline\">Create Account</button><p class=\"text-center mt-4 mb-4 opacity-50\">Or, for passwordless login</p><button class=\"w-full lg:w-1/2 transition-all hover:scale-105 text-black py-2 px-4 border-black border-solid border rounded-[8px] focus:outline-none focus:shadow-outline\">Sign up with Google</button></form></div></div><div class=\"flex flex-col items-center w-full lg:w-auto\"><img src=\"/public/images/girl-yellow.png\" class=\"hidden lg:block w-[32vw] lg:max-w-[600px] mt-8\"><div class=\"flex flex-col bg-green-500 p-[1.5px] lg:p-[5px] rounded-[10px] lg:rounded-[16px] w-full lg:w-fit mt-[14px]\"><div class=\"bg-green-500 flex gap-x-[4px] lg:gap-x-[6px] p-[6px] lg:p-2.5 rounded-t-[10px] lg:rounded-t-[16px]\"><div class=\"bg-white rounded-full w-[9px] h-[9px] lg:w-[12px] lg:h-[12px]\"></div><div class=\"bg-white rounded-full w-[9px] h-[9px] lg:w-[12px] lg:h-[12px]\"></div><div class=\"bg-white rounded-full w-[9px] h-[9px] lg:w-[12px] lg:h-[12px]\"></div></div><div class=\"bg-white rounded-b-[10px] lg:rounded-b-[16px] p-6 \"><div class=\"w-full lg:w-fit bg-pink-700 hover:bg-pink-500 transition-all text-white font-bold py-2 px-4 rounded-[8px] focus:outline-none focus:shadow-outline flex items-center justify-center\"><a href=\"/login\">Switch to Sign in</a></div></div></div></div></div></div><script>\n  document.addEventListener(\"htmx:responseError\", function (event) {\n    if (event.detail.xhr.status === 400) {\n      var errorMessage = JSON.parse(event.detail.xhr.responseText).error;\n      document.getElementById(\"error-message\").innerText = errorMessage;\n    }\n  });\n</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
