// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Navbar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"w-full flex justify-between items-center px-9 py-0 sm:py-0 border-pink-700 border-b-[3px] sm:border-b-[10px]\"><a href=\"/\"><img src=\"/public/images/text_logo.png\" alt=\"Text logo - Neurokin\" width=\"170\" height=\"70\" class=\"mt-4 sm:mt-0\"></a> <menu class=\"text-pink-700 text-lg gap-x-11 sm:flex items-center hidden\"><a href=\"/about\">About</a> <a href=\"/pricing\">Pricing</a> <a href=\"/login\">Login</a> <a href=\"/signup\" class=\"bg-pink-700 text-white px-4 py-2 rounded-lg\">Sign Up</a></menu><div class=\"sm:hidden\"><button><div class=\"flex flex-col items-center\"><div class=\"w-6 h-[2px] bg-black mb-1\"></div><div class=\"w-6 h-[2px] bg-black mb-1\"></div><div class=\"w-6 h-[2px] bg-black mb-1\"></div></div></button></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
