// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Section1() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"min-h-screen flex flex-col items-center justify-center bg-pink-500 xl:min-h-[753px]\"><div class=\"h-[115px] w-full hidden md:flex\"></div><div class=\"container px-8 xl:w-[70%] flex items-center justify-center\"><div class=\"flex flex-col container bg-green-500 p-[5px] rounded-[16px] overflow-hidden\"><div class=\"bg-green-500 flex gap-x-[6px] p-2.5\"><div class=\"bg-white rounded-full w-[12px] h-[12px]\"></div><div class=\"bg-white rounded-full w-[12px] h-[12px]\"></div><div class=\"bg-white rounded-full w-[12px] h-[12px]\"></div></div><div class=\"bg-white w-full rounded-b-[16px] p-6 text-[36px] md:text-[82px] grid leading-none font-display font-semibold md:px-24 lg:py-8 gap-y-4\"><div class=\"w-full flex items-center gap-x-10\"><h1 class=\"\">Bridging</h1><div class=\"h-full w-full bg-pink-700 flex-1\"></div></div><div class=\"w-full flex items-center gap-x-10 flex-1\"><h1 class=\"\">The Gap To</h1><div class=\"h-full w-full bg-green-700 flex-1\"></div></div><div class=\"w-full flex flex-row items-center gap-x-10\"><div class=\"grid gap-y-4 w-full max-w-[425px]\"><h1 class=\"w-full\">Diagnosis</h1><div class=\"h-full w-full bg-red-500\"></div><div class=\"text-[10px] md:text-[16px] leading-none font-anek font-normal bg-green-700 text-center p-4 flex items-center justify-center overflow-hidden max-h-[7rem] border-black border-[2px] rounded-[4px] w-full\">Welcome to Neurokin, a platform committed to creating a safer and more inclusive space for underrepresented folks of color to bridge the gap to ADHD/Autism diagnosis.</div></div><div class=\"h-full w-full bg-red-500\"></div></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
