package quizzes

import (
	t "neurokin/types"
)

var AspieQuestions = []t.QuizQuestion{
	{
		Question: "Do you tend to get so absorbed by your special interests that you forget or ignore everything else?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F001",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have an avid perseverance in gathering and/or cataloguing information on a topic of interest?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F002",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Is it important for you to find a unique niche where you can acquire unique competence?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F003",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have an urge to observe the habits of humans and/or animals?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F004",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you notice patterns in things all the time?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F005",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have one special talent which you have emphasized and worked on?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F006",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you like to create routines for things you've figured out so you don't have to figure it out again?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F007",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you feel that you are a very special or unusual person?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F008",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Can things that might seem meaningless to others make sense to you?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F009",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Are you still fascinated by many of the things you were interested in when you were much younger?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F010",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you prefer to construct your own set of spiritual beliefs rather than following existing religions / belief-systems?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F011",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Is it difficult to pass on messages correctly?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F012",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you get confused by several verbal instructions at the same time?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F013",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have difficulty describing & summarising things, for example, events, conversations, or something you've read?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F014",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you tend to wander off the topic when having a conversation?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F015",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have problems filling out forms?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F016",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you find it difficult to take notes in lectures?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F017",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "If there is an interruption, can you quickly return to what you were doing before?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F018",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you need to do things yourself in order to remember them?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F019",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you find it difficult to engage in a task of no interest to you even if it is important?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F020",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you need a lot of motivation to do things?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F021",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Are you bothered by clothes tags or light touch?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F022",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you tend to shut down or have a meltdown when stressed or overwhelmed?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F023",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Are your eyes extra sensitive to strong light and glare?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F024",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you dislike when people walk behind you?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F025",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have extra sensitive hearing?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F026",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Are you sensitive to changes in humidity and air pressure?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F027",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you dislike being hugged when you haven't asked for it?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F028",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you dislike it when people stamp their foot on the floor?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F029",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you notice odors that other people don't seem to notice?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F030",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you instinctively become frightened by the sound of a motorbike?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F031",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you instinctively know when it is your turn to speak when talking on the phone?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F032",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have problems with timing in conversations?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F033",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have difficulties judging distances, height, depth, or speed?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F034",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have problems finding your way to new places?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F035",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you find it hard to tell the age of people?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F036",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Are you good at interpreting facial expressions?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F037",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have a good sense of time?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F038",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you find it easy to describe your feelings?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F039",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have a good sense of how much pressure to apply when doing things with your hands?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F040",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have trouble reading clocks?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F041",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you recognize a lot of people?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F042",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you wring your hands, rub your hands together or twirl your fingers?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F043",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you rock back-and-forth or side-to-side (e.g. for comfort, to calm yourself, when excited or overstimulated)?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F044",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you tap your ears or press your eyes (e.g. when thinking, when stressed or distressed)?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F045",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have obsessive attachments to animate objects?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F046",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Are you often delighted by small things (like the colors in soap bubbles and the five-pointed star shape that appears when you cut an apple across the core)?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F047",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "When you listen to music, can you get so caught up in it that you don't notice anything else?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F048",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you like to follow (walk behind) people you are attached to?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F049",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have a fascination for slowly flowing water?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F050",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you feel an urge to peel flakes off yourself and/or others?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F051",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you pace (e.g. when thinking or anxious)?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F052",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you examine the hair of people you like a lot?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F053",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you bite your lip, cheek, or tongue (e.g. when thinking, when anxious or nervous)?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F054",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you enjoy spinning in circles?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F055",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you tend to play the same tune many times in a row?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F056",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have an urge to jump over things?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F057",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you tend to express your feelings in ways that may baffle others?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F058",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "As a teenager, were you usually unaware of social rules & boundaries unless they were clearly spelled out?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F059",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you tend to say things that are considered socially inappropriate when you are tired, frustrated, or when you act naturally?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F060",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you find it easier to understand and communicate with odd & unusual people than with ordinary people?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F061",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do others often misunderstand you?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F062",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do people sometimes think you are smiling at the wrong occasion?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F063",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Is your sense of humor different from mainstream or considered odd?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F064",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Have others told you that you have an odd posture or gait?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F065",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you tend to interpret things literally?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F066",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Is it hard for you to see why some things upset people so much?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F067",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you fail to understand pop culture, things like 'being in style' or why people jump onto the latest trend?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F068",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Have you been accused of staring?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F069",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have to keep an eye out to stop people from taking advantage of you?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F070",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you feel as if you are being persecuted in some way?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F071",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Have you experienced stronger than normal attachments to certain people?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F072",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Have you sensed that somebody was around you even when you couldn't see anybody?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F073",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you worry your friend doesn't really like you?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F074",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you realize hours later that somebody that you have a romantic interest for actually showed interest for you, and then feel bad about the missed opportunity to connect?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F075",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you tend to look a lot at people you like and little or not at all at people you dislike?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F076",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have, or used to have, imaginary relationships?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F077",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have unusual sexual preferences?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F078",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Did you feel lonely as a child?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F079",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you prefer to learn the character of a potential romantic partner through observation rather than conversation?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F080",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you cry about nothing?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F081",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you like to protect people you are attached to even when they didn't ask for it?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F082",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Have you been talked into having sex even if you really didn't want to?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F083",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you tend to get romantic feelings for people that persistently show interest in you?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F084",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Are you good at teamwork?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F085",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you find it natural to wave or say 'hi' when you meet people?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F086",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you find it easy to keep up with group discussions where everyone is speaking?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F087",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you enjoy traditional dating?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F088",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you find yourself at ease in romantic situations?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F089",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you enjoy big events even if they are crowded?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F090",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you enjoy travel?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F091",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you like to have small talk before getting on to the important topics in a conversation?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F092",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you like tongue-kissing?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F093",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you naturally approach somebody you have a romantic interest in?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F094",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you like 'being in style'?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F095",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Are you asexual?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F096",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Would you quickly become impatient and irritated if you would not find a solution to a problem?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F097",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "In a conversation, do you tend to focus on your own thoughts rather than on what your listener might be thinking?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F098",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you have difficulty accepting criticism, correction, and direction?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F099",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you expect other people to know your thoughts, experiences, and opinions without you having to tell them?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F100",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you usually find faults with opinions that you don't share?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F101",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you see your own activities as more important than other people's?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F102",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you feel irritated when one person disagrees with what everyone else in a group believes?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F103",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Will you abandon your friends if your activities or ideals clash?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F104",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you avoid talking because you cannot reliably predict how others will react, especially strangers?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F105",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Has it been harder for you than for others to keep friends?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F106",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "In conversations, do you need extra time to carefully think out your reply, so that there may be a pause before you answer?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F107",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you need to prepare yourself mentally before going somewhere?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F108",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you feel you have to be on your guard even with friends?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F109",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you practice what you want to say in conversations?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F110",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you spend hours overthinking and re-enacting negative social interaction?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F111",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you dislike it when people drop by to visit you uninvited?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F112",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you prefer to do things on your own even if you could use others' help or expertise?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F113",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you prefer to only meet people you know, one-on-one, or in small, familiar groups?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F114",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Are you shy?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F115",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Is your sense of humor fairly conventional?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F116",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Can you easily remember verbal instructions?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F117",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you find it easy to estimate the age of people?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F118",
		Type:     t.QTypeMultipleChoice,
	},
	{
		Question: "Do you accept criticism, correction, and direction?",
		Answers:  []string{"I don't know", "No/Never", "A little", "Yes/Often"},
		Id:       "F119",
		Type:     t.QTypeMultipleChoice,
	},
}

var AspieQuiz = t.Quiz{
	Name:     "Aspie Quiz",
	Slug:     "aspie",
	Questions: AspieQuestions,
}

